version: "3.7"

services:
  wordpress:
    build: .
    restart: always
    ports:
      - "8084:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mysql
      WORDPRESS_DB_PASSWORD: mysql
      WORDPRESS_DB_NAME: dbwp
    volumes:
      - ./src:/var/www/html/wp-content/plugins/plugin

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: dbwp
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8888:80"

networks:
  back:

volumes:
  db:
